Add support for CESIUM_RTC in GltfLoader
CesiumGS/cesium pull request #10628
Opened 2022-08-02 23:23 UTC by lilleyse

Part of https://github.com/CesiumGS/cesium/issues/10613

[CESIUM_RTC](https://github.com/KhronosGroup/glTF/blob/main/extensions/1.0/Vendor/CESIUM_RTC/README.md) is used in a lot of glTF 1.0 assets and was easy enough to support in `GltfLoader`.

2022-08-02 23:23 UTC, cesium-concierge commented
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/cesium-rtc/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

2022-08-03 14:05 UTC, j9liu requested changes
@lilleyse just a few comments! Also, should this go in `CHANGES.md`?

2022-08-03 15:18 UTC, j9liu commented on Specs/Scene/GltfLoaderSpec.js
> +    it("loads model with CESIUM_RTC", function () {
Actually, just noticed #10627 so this unit test won't work. I'll add this when I work on a fix.

2022-08-04 11:58 UTC, lilleyse commented on Source/Scene/ModelExperimental/B3dmLoader.js
> +      components.transform = Matrix4.multiplyTransformation(
Yeah, both do the same thing. `CESIUM_RTC` started as a glTF 1.0 extension which later became the `RTC_CENTER` property in the feature table. And typically only one is defined (I've never seen both at the same time)

2022-08-04 11:58 UTC, lilleyse commented on Source/Scene/ModelExperimental/B3dmLoader.js
> +      components.transform = Matrix4.multiplyTransformation(
Maybe... I haven't seen an i3dm use `CESIUM_RTC` but I pushed a commit for that just in case.

2022-08-04 12:01 UTC, lilleyse commented
@j9liu ready for another look.

> Also, should this go in `CHANGES.md`?

I don't think it needs to since it's giving `ModelExperimental` the same functionality that `Model` already has, and `ModelExperimental` will soon be going away.

2022-08-04 13:54 UTC, j9liu commented
@lilleyse looks good, I'll merge now. Thanks!

2022-08-04 13:55 UTC, merged