Vignesh patch
CesiumGS/cesium pull request #11406
Opened 2023-07-07 14:06 UTC by neshvig10

2023-07-07 14:07 UTC, cesium-concierge commented
Thanks for the pull request @neshvig10!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

2023-07-11 15:18 UTC, jjhembd requested changes
Thanks @neshvig10, this should be a good optimization! I just have 2 suggestions.

2023-07-11 15:18 UTC, jjhembd commented on CHANGES.md
> +-fixed a typo in line 88 of PolylineCommon.glsl
This change should be listed at the top of the file, under "Fixes" in the 1.108 release. 
Also, I don't think this is really a typo. The old code was correct, but your code will be faster. Perhaps you could say "optimized angle calculations in Polyline shader"

2023-07-11 15:18 UTC, jjhembd commented on Source/Shaders/PolylineCommon.glsl
> +    angle = czm_fastApproximateAtan(lineDir.x, lineDir.y) - 1.570796327; // precomputed czm_fastApproximateAtan(1,0)
If we replace the constant `1.570796327` with `czm_piOverTwo`, the code will be more self-explanatory, so the comment won't be necessary.

2023-07-15 14:02 UTC, closed without merging