docs: Improve the types of Billboard&BillboardCollection.add and Label&LabelCollection.add
CesiumGS/cesium pull request #11864
Opened 2024-02-27 16:09 UTC by s3xysteak

# Description

Reopen [a closed PR](https://github.com/CesiumGS/cesium/pull/11831) because the PR missed some properties.
I think I have signed the CLA this time, sorry for my previous carelessness :pray: .

It improves the types of Billboard&BillboardCollection.add and Label&LabelCollection.add.

Fix a doc bug that they both do not contain disableDepthTestDistance in option, which should be contained.
Add types about the constructOptions of Label and Billboard. They are copy from BillboardGraphics / LabelGraphics.

Future improvement:
I think it may be need a little discussion that The [BillboardGraphics](https://github.com/CesiumGS/cesium/blob/1.114/packages/engine/Source/DataSources/BillboardGraphics.js#L50) and [LabelGraphics](https://github.com/CesiumGS/cesium/blob/1.114/packages/engine/Source/DataSources/LabelGraphics.js#L8) already have similar type declarations. Should I
use the type declarations here directly in Billboard and Label,
or declare them in Billboard and Label and then reference them elsewhere,
or simply copy the type declarations and use them in both Label and LabelCollection?

I believe both approaches would not have any impact on the usage of the code (including TypeScript users). However, a less optimal solution might cause confusion during future maintenance.

## Issue number and link

see #11813.

## Testing plan

The PR is only about docs. Run build-docs and build-ts, and check the effect.
Before: BillboardCollection.add and LabelCollection.add have no intellisense.
After: They should have correct intellisense.

Run npm run build-docs to confirm the document should be correct to show the information.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [x] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

2024-02-28 03:19 UTC, s3xysteak commented
I checked the result of `build-docs` and `build-ts` again. There should not be any more obvious mistakes then.

2024-03-05 14:33 UTC, ggetz requested changes
Thanks @syzdev! I have some suggestion about the description wording.

2024-03-05 14:33 UTC, ggetz commented on packages/engine/Source/Scene/Billboard.js
> + * @property {boolean} [show=true] A boolean Property specifying the visibility of the billboard.
```suggestion
 * @property {boolean} [show=true] Determines if this billboard will be shown. 
```

2024-03-05 14:33 UTC, ggetz commented on packages/engine/Source/Scene/Billboard.js
> + * @property {boolean} [show=true] A boolean Property specifying the visibility of the billboard.
For this and for all the following properties, please remove the mention of "Property".

2024-03-06 14:14 UTC, ggetz commented
Great, thanks @s3xysteak! Congrats on your first PR! 🎉

2024-03-06 14:14 UTC, merged