Deprecation Updates for SceneTransforms Methods
CesiumGS/cesium pull request #12156
Opened 2024-08-27 02:44 UTC by jvrjsanchez

# Description

## Issue number and link

## Testing plan

# Author checklist

- [ ] I have submitted a Contributor License Agreement
- [ ] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [ ] I have performed a self-review of my code

2024-08-27 13:20 UTC, ggetz requested changes
Great, thanks @jvrjsanchez! I have a few comments on the code that should be addressed before we can merge this.

2024-08-27 13:20 UTC, ggetz commented on package.json
> +    "cesium": "^1.120.0"
Please remove this unrelated change.

2024-08-27 13:20 UTC, ggetz commented on CHANGES.md
> +
Changes should all go under the next scheduled release, `### 1.121 - 2024-09-01`.

2024-08-27 13:20 UTC, ggetz commented on CHANGES.md
> +
I would replace this all with:

```
- `SceneTransforms.wgs84ToWindowCoordinates` has been removed. Use `SceneTransforms.worldToWindowCoordinates` instead.
- `SceneTransforms.wgs84ToDrawingBufferCoordinates` has been removed. Use `SceneTransforms.worldToDrawingBufferCoordinates` instead.
```

and put it under the 

`##### Breaking Changes :mega:` 

section.

2024-08-30 19:51 UTC, jjspace commented
@jvrjsanchez Our monthly release happens on Tuesday and this needs to make it into that. In the interest of time because we have a long weekend I made some final touches on this to get it over the finish line. Thanks for your work on the PR.

2024-08-30 20:26 UTC, ggetz approved these changes

2024-08-30 20:26 UTC, ggetz commented
Thanks all!

2024-08-30 20:26 UTC, merged