per naming convention and #4921 this should make this `Rectangle.validate` private.
CesiumGS/cesium pull request #12212
Opened 2024-09-23 22:26 UTC by hotpocket

# Description
The `Rectangle.validate` function is only called in pragmas and has thus been an empty function call.  Per issue #4921 it was suggested to make this private, presumably so that this behavior is explicit. 

## Testing plan
All tests pass that were previously passing.  There was one test that failed on my Ubuntu 22.04.05 OS.  This is listed below:
```
TOTAL: 1 FAILED, 14300 SUCCESS

1) renders a point
     Scene/Vector3DTilePoints
     Expected to render [255,255,255,255], but actually rendered [254,254,254,255].
    at <Jasmine>
    at packages/engine/Specs/Scene/Vector3DTilePointsSpec.js:177:25 <- Build/Specs/SpecList.js:236887:24
```
This test was failing on unmodified version of main with the command `npm run test`. I assume this is "ok" with respect to this issue. 

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

2024-09-23 22:37 UTC, ggetz commented
@jjspace Could you please give this a review?

2024-09-24 14:02 UTC, jjspace requested changes
This is looking good, just a few more steps to make sure changes to the public API are make responsibly.

2024-09-24 14:02 UTC, jjspace commented on packages/engine/Source/Core/Rectangle.js
> +Rectangle._validate = function (rectangle) {
As we discussed last night we should go through the deprecation process for this function. You can read about it in our [Coding Guide](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CodingGuide/README.md#deprecation-and-breaking-changes). Basically rename this function but also add the `Rectangle.validate` function back which just calls through to this one and has the `@deprecated` tag and `deprecatedWarning`.

2024-09-26 22:37 UTC, hotpocket commented
@jjspace I believe this is ready.

2024-09-27 15:37 UTC, jjspace approved these changes
Looks good to me now, thanks @hotpocket!

2024-09-27 20:24 UTC, jjspace approved these changes
Sorry for any noise this caused in your notifications @hotpocket, we just [updated prettier](https://github.com/CesiumGS/cesium/pull/12206) and I was trying to update your branch for you but turned out a little trickier than I thought but that was on my side.

This is finally good to go now

2024-09-27 20:26 UTC, lukemckinstry approved these changes
Approving following @jjspace's Prettier updates

2024-09-27 20:27 UTC, merged

2024-09-27 20:53 UTC, hotpocket commented
> Sorry for any noise this caused in your notifications @hotpocket, we just [updated prettier](https://github.com/CesiumGS/cesium/pull/12206) and I was trying to update your branch for you but turned out a little trickier than I thought but that was on my side.
> 
> This is finally good to go now

I am comforted to know that I am not the only one that still fights with git :slightly_smiling_face: ([xkcd](https://xkcd.com/1597/)).  Thanks @jjspace