Fixed Matrix Multiplication Shaders
CesiumGS/cesium pull request #12349
Opened 2024-12-01 09:10 UTC by GGajanan1

# Description

Fixed Matrix Multiplication in shaders
fixes #4250 

## Issue number and link

## Testing plan

# Author checklist

- [ ] I have submitted a Contributor License Agreement
- [ ] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [ ] I have performed a self-review of my code

2024-12-03 07:40 UTC, GGajanan1 commented
> Thank you for the pull request, @GGajanan1! Welcome to the Cesium community!
> 
> In order for us to review your PR, please complete the following steps:
> 
> * [X]  Send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA)
> * [ ]  Add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTORS.md) file
> 
> Review [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) to make sure your PR gets accepted quickly.

2024-12-09 19:12 UTC, ggetz commented
Thanks @GGajanan1! I can confirm we have a CLA on file for you now.

2024-12-09 19:18 UTC, ggetz reviewed
Thanks for the changes so far @GGajanan1!

I think there are a few other places where this update is needed as well:
- `DepthPlaneVS.glsl`
- `EllipsoidVS.glsl`
- `GlobeVS.glsl`
- `modelToWindowCoordinates.glsl`

2024-12-10 10:35 UTC, GGajanan1 commented
@ggetz  Thanks , I have did the changes in the following PR:https://github.com/CesiumGS/cesium/pull/12367

2025-01-02 16:25 UTC, ggetz commented
Thanks @GGajanan1! 

* Is it possible to bring your changes from https://github.com/CesiumGS/cesium/pull/12349 into this branch as well?
* Please update `CONTRIBUTORS.md` to include your username

2025-01-02 16:47 UTC, GGajanan1 commented
@ggetz  I have merged the changes from #12367  in this current branch.

2025-01-02 16:55 UTC, GGajanan1 commented
Also added my name in CONTRIBUTORS.md

2025-01-06 16:20 UTC, ggetz commented
Perfect, thanks @GGajanan1! 

We typically don't assign issues except for our own internal issue on the Cesium team.

2025-01-08 16:28 UTC, jjhembd requested changes
@GGajanan1 thanks a lot for this work! 
I'm still testing on my end to verify the rendering result. Meanwhile, I have one comment about a typo in `MultifrustumSpec` below.

2025-01-08 16:28 UTC, jjhembd commented on packages/engine/Specs/Scene/MultifrustumSpec.js
> +          vs += "    vec4 positionEC = czm_modelView * positiong; l_Position = czm_projection * positionEC;";
There is a typo here: this line should be split across 2 lines.

We generally want to use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) instead of string concatenation. See https://github.com/CesiumGS/cesium/pull/10067. This typo is a good example of why: manually adding up strings is hard to read and easy to make a small mistake.

Can you update this section to use a template literal?

2025-01-08 19:20 UTC, GGajanan1 commented
I have added the changes

2025-01-10 02:29 UTC, jjhembd requested changes
Hi @GGajanan1, thanks for the update!
I looked through a little more closely, and noticed a few things in the code. Once these are fixed, I can run the rendering tests to confirm.

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Source/Shaders/Builtin/Functions/modelToWindowCoordinates.glsl
> +    q = czm_projection * positionEC;
`q` was not declared. The first use of it should include the type: 
```glsl
vec4 q = ...
```

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Source/Shaders/DepthPlaneVS.glsl
> +    gl_Position = czm_projection * positionEC;
I don't think we need this change. Now we are redeclaring `positionEC`, and defining `gl_Position` twice.

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Source/Shaders/EllipsoidVS.glsl
> +    vec4 positionEC = czm_modelView * position;
This change is now multiplying by `czm_modelView` twice, which will affect performance. We could do the multiplication once, then re-use the result for the `vec3` variable.
```glsl
vec4 pEC = czm_modelView * p;
v_positionEC = pEC.xyz;
```

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Source/Shaders/EllipsoidVS.glsl
> +    gl_Position = czm_projection * positionEC;
`positionEC` is not the same as `p`, so this is changing the result.

With the change from the previous comment, this line could be:
```glsl
gl_Position = czm_projection * pEC;
```

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Source/Shaders/GlobeVS.glsl
> +    vec4 positionEC = czm_modelView * position;
This is significantly changing the output. For a consistent result, this could be:
```glsl
vec4 positionEC = czm_modelView * morphPosition;
```

However, we may want to avoid using the `positionEC` name for modified positions, because that name has a very specific meaning in most of the rest of the code.

2025-01-10 02:29 UTC, jjhembd commented on packages/engine/Specs/Scene/MultifrustumSpec.js
> +              gl_Position = czm_modelViewProjection * position;
I think this is a copy-pasting error. `gl_Position` is now defined twice.

2025-07-29 18:54 UTC, jjhembd approved these changes
@GGajanan1 I pushed a commit implementing my commits. This should be ready to go once we add a note to CHANGES.md

2025-07-29 18:59 UTC, merged