Splat shader
CesiumGS/cesium pull request #12364
Opened 2024-12-06 19:00 UTC by keyboardspecialist

# Description

Opening as a draft as some things are still in progress, and this is a long running feature branch.

This adds support for rendering Gaussian splats from 3D Tiles 1.1 using a proposed draft extension [here](https://github.com/KhronosGroup/glTF/issues/2454)

Support added for integer textures with pixel formats R32UI/R32I, RG32UI/RG32I, RGB32UI/RGB32I.

## Issue number and link

## Testing plan

TBD. Will include a sandcastle.

# Author checklist

- [ ] I have submitted a Contributor License Agreement
- [ ] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [ ] I have performed a self-review of my code

2024-12-06 19:38 UTC, ggetz commented
Hi @keyboardspecialist! I can confirm we have a CLA on file for you.

The first step here will be merging in `main`, which may be a bit more involved since this branch appears to have been created since we last update prettier. To minimize the formatting conflicts, please follow [these instructions](https://community.cesium.com/t/cesiumjs-updated-prettier-to-version-3-3-3/35473) as part of your process of merging `main`, and add a comment when this is ready for a look. Thanks!

2024-12-13 16:17 UTC, ggetz commented
@keyboardspecialist I'm bumping my comment above, as it's preventing us from being able to effectively review this PR. If you have any questions or concerns, please let us know!

Meanwhile, I did leave a review on https://github.com/CesiumGS/cesium-wasm-utils/pull/1, which encapsulates the wasm aspect of this feature.

2025-01-16 19:42 UTC, ggetz requested changes
Thanks for getting this fixed up after the prettier updates @keyboardspecialist! It really helped with the diff.

* I notice there are [several failing unit tests in CI](https://github.com/CesiumGS/cesium/actions/runs/12812937998/job/35725802214?pr=12364#step:6:17).
* I didn't see any unit tests for the new functionality or files. These will need to be added before the PR can be merged. We typically aim for code coverage of ~90% or more for new code.

2025-01-16 19:42 UTC, ggetz commented on packages/engine/Source/Shaders/Model/GaussianSplatVS.glsl
> +void calcCov3D(vec3 scale, vec4 rot, out float[6] cov3D)
@lilleyse Should probably be the one to do a pass on the shaders.

2025-01-17 15:50 UTC, weegeekps commented on temp_wasm/pkg/README.md
> +<div align="center">
Correct. I added the TODO item to the PR description.

2025-01-17 15:52 UTC, weegeekps commented on package.json
> +    "@cesium/wasm-splats": "file:./temp_wasm/pkg"
I will fix this when I move to using the published package.

2025-01-17 22:54 UTC, keyboardspecialist commented on scripts/build.js
> +
Unneeded. I merged the version from main.

2025-01-17 22:55 UTC, keyboardspecialist commented on Apps/Sandcastle/gallery/3D Tiles Gaussian Splatting.html
> +      content="Use Viewer to start building new applications or easily embed Cesium into existing applications."
Updated to a relevant description

"Load 3D Tiles 1.1 Gaussian Splats dataset of a cell tower"

2025-01-17 22:56 UTC, keyboardspecialist commented on packages/engine/Source/Renderer/Context.js
> +  webglOptions.alpha = defaultValue(webglOptions.alpha, true); // WebGL default is true
Erroneous change. Reverted back to false.

2025-01-17 22:58 UTC, keyboardspecialist commented on packages/engine/Source/Renderer/Texture.js
> +  if (glErr !== 0) {
I simply removed these as they were more for debugging than actually reporting an error to the user. Main doesn't handle any errors here, but if we want to I can put it back in. At least in the second case when the texture is actually created.

2025-01-17 22:58 UTC, keyboardspecialist commented on packages/engine/Source/Renderer/VertexArray.js
> +        // vaAttributes.push({
Removed

2025-01-17 23:07 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/GaussianSplatPipelineStage.js
> +// class CesiumPerformanceTimer {
Removed

2025-01-17 23:08 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/GaussianSplatPipelineStage.js
> +  const cam = frameState.camera;
Variables renamed to be more descriptive.

2025-01-17 23:12 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/GeometryPipelineStage.js
> +      shaderBuilder.addDefine("PRIMITIVE_TYPE_POINTS");
Reworked to remove the else

2025-01-17 23:12 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +//import Buffer from "../../Renderer/Buffer.js";
Removed.

2025-01-17 23:24 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +  const viewProj = new Matrix4();
Is there a preferred alternative to scratch? Because of the async sorting module scope scratch variables will get clobbered when we don't want them to.

2025-01-17 23:24 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +  if (model._previousViewProj === undefined) {
Switched to define()

2025-01-17 23:26 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +    return;
It was, but this should change. An initial sort needs to occur.

2025-01-17 23:26 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +    if (prim?.isGaussianSplatPrimitive ?? false) {
Superfluous false removed.

2025-01-17 23:27 UTC, keyboardspecialist commented on packages/engine/Source/Shaders/Model/ModelVS.glsl
> +    #ifdef HAS_CUSTOM_VERTEX_SHADER
This indentation was lost at some point, and I don't know why. Re-added.

2025-01-17 23:27 UTC, keyboardspecialist commented on packages/engine/Source/Workers/gaussianSplatTextureGenerator.js
> +//import defaultValue from "../Core/defaultValue.js";
Removed

2025-01-17 23:27 UTC, keyboardspecialist commented on packages/engine/Source/Workers/gaussianSplatSorter.js
> +//import defaultValue from "../Core/defaultValue.js";
Removed

2025-01-17 23:27 UTC, keyboardspecialist commented on packages/engine/Source/Workers/gaussianSplatSorter.js
> +      2048,
It was picked as a maximally compatible texture width.

2025-01-17 23:28 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +      const modelView = new Matrix4();
Like the view matrix, this will get clobbered if module scoped.

2025-01-21 20:03 UTC, ggetz commented on packages/engine/Source/Scene/Model/Model.js
> +      const modelView = new Matrix4();
I might have missed something, but you're using this instance only here and a few lines below at 2232. I don't think there's race condition that could affect the value in between that.

2025-01-21 20:03 UTC, ggetz commented on packages/engine/Source/Workers/gaussianSplatSorter.js
> +      2048,
OK. Perhaps this should be defined as a constant somewhere then to make this a bit more explanatory.

2025-01-24 15:30 UTC, keyboardspecialist commented on gulpfile.js
> +  copyFileSync(
No problem. I moved it up.

2025-01-24 15:33 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +        this.type !== ModelType.GLTF
Yes it would. TILE_GLTF added to the check.

2025-01-24 15:34 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +        this._enableShowGaussianSplatting === true ||
That is correct. Updated logic.

2025-01-24 17:02 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/GaussianSplatPipelineStage.js
> +    const posAttr = attributes.find((a) => a.name === "POSITION");
These were already added to VertexAttributeSemantics, I just needed to actually use them.

2025-01-24 21:09 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +  const viewProj = new Matrix4();
Something else was going on that's beyond my Javascript knowledge. Using module or instance scoped matrices caused the check to always fail as the difference would always be impossibly small regardless of how much you rotated the camera. Switching back to local with no other changes fixed it.

Ultimately, the solution was to just simplify everything and just let it sort.

2025-01-24 21:10 UTC, keyboardspecialist commented on packages/engine/Source/Scene/Model/Model.js
> +      const modelView = new Matrix4();
This matrix was moved to a scratch var.

2025-01-27 17:50 UTC, ggetz commented
Thanks for all the updates here @keyboardspecialist!

What is the current status of this PR and where can we help with reviews?

- Is the code ready for another review pass?
- What is the status of unit tests?
- What does a testing plan look like for us to confirm functionality?
- Is the inline documentation up to date?
- Has `GaussianSplatTextureGenerator` been updated as per the TODO list item?

2025-02-03 14:18 UTC, keyboardspecialist commented
> Thanks for all the updates here @keyboardspecialist!
> 
> What is the current status of this PR and where can we help with reviews?
> 
> * Is the code ready for another review pass?
> * What is the status of unit tests?
> * What does a testing plan look like for us to confirm functionality?
> * Is the inline documentation up to date?
> * Has `GaussianSplatTextureGenerator` been updated as per the TODO list item?

* Code is ready for another pass
* Unit tests are being wrapped up
* I'm putting together some simple assets for tests, compressed and uncompressed. It's using the model pipeline, so it's mainly checking that it's loading the glTF correctly and setting the pipeline state.
* Documentation in progress
* Yes, all code changes are complete.

2025-04-25 16:43 UTC, keyboardspecialist commented
Closing this PR as other work has superseded it in the https://github.com/CesiumGS/cesium/tree/splat-spz-concept branch

2025-04-25 16:43 UTC, closed without merging

2025-04-25 16:43 UTC, Hiwen commented
谢谢，您的邮件我已经收到，收到邮件后，我会在第一时间回复您。祝一切顺利！