feat: remove redundant param for `writeTextToCanvas`
CesiumGS/cesium pull request #12376
Opened 2024-12-17 06:58 UTC by ibreathebsb

# Description

This pull request removes redundant  parameter `textBaseline`  which is not used in `writeTextToCanvas`

# Author checklist

- [ x ] I have submitted a Contributor License Agreement
- [ x ] I have added my name to `CONTRIBUTORS.md`
- [ x ] I have updated `CHANGES.md` with a short summary of my change (**no need acutally**)
- [ x ] I have added or updated unit tests to ensure consistent code coverage
- [ x ] I have updated the inline documentation, and included code examples where relevant
- [ x ] I have performed a self-review of my code

2024-12-18 20:32 UTC, javagl commented
For me, it looks like this can indeed safely be removed. 

There are some broader issues with that function, though - just as cross-references: https://github.com/CesiumGS/cesium/issues/9767 , https://github.com/CesiumGS/cesium/pull/11747 , ...

2025-01-02 16:22 UTC, ggetz commented
Thanks for the cleanup @ibreathebsb!

@jjspace Could you please take a review pass on this PR?

2025-01-07 21:01 UTC, jjspace requested changes
You are correct that that option is unused. I was curious _why_ and whether it _should_ be used and found this old comment in a previous rewrite of this function https://github.com/CesiumGS/cesium/pull/9765#discussion_r698725603 that removed the place it was used.

I think this is good to go. Please merge in `main` to fix the conflicts.
It looks like you skipped running prettier somehow. please run `npm run prettier` and also make sure the pre-commit git hook is set up correctly.

2025-01-08 10:13 UTC, ibreathebsb commented
> You are correct that that option is unused. I was curious _why_ and whether it _should_ be used and found this old comment in a previous rewrite of this function [#9765 (comment)](https://github.com/CesiumGS/cesium/pull/9765#discussion_r698725603) that removed the place it was used.
> 
> I think this is good to go. Please merge in `main` to fix the conflicts. It looks like you skipped running prettier somehow. please run `npm run prettier` and also make sure the pre-commit git hook is set up correctly.

I have fixed prettier and git hooks issues,resolved conflicts

2025-01-08 20:41 UTC, jjspace approved these changes
Thanks for the changes @ibreathebsb, this looks good to go now.

The release tests in CI keep failing on the `npm install` step with what looks like connection issues. I'm currently assuming this might be something weird on Github's side so I'm gonna give it some time and try re-running them later and then hopefully it will be good to merge.

2025-01-10 18:37 UTC, merged