types: mark `options` param of ImageryLayer.fromProviderAsync as optional
CesiumGS/cesium pull request #12400
Opened 2024-12-29 22:02 UTC by NickCrews

As the examples show, it is perfectly fine to not pass in the options object. However, in my typescript project, if I don't pass in the options, I get a type error. This is intended to fix that error.

This was brought up in https://community.cesium.com/t/error-when-initialize-imagerylayer-fromproviderasync-without-options/31665

I'm not used to typescript/jsdoc at all, so this might not actually be the right way to do this. If you tell me how to do this,
let me know and I can update it.

2024-12-29 22:05 UTC, NickCrews commented
I just signed the CLA. I don't personally need myself in the contributors file. If YOU require me in there, I can add myself.

2025-01-03 18:16 UTC, jjspace requested changes
Thanks for the PR! Just had one small comment.

> If YOU require me in there, I can add myself.

Yes, if you could please add yourself that would be great :pray:

2025-01-04 01:08 UTC, NickCrews commented on packages/engine/Source/Scene/ImageryLayer.js
> + * @param {ImageryLayer.ConstructorOptions|undefined} options An object describing initialization options
Thanks! I added some fixup commits that addressed this.

2025-01-04 01:08 UTC, NickCrews commented
I added myself to contributors and adjusted the docstring. Thank you! @jjspace

2025-01-06 16:14 UTC, ggetz commented
Thanks @NickCrews! Since this affects the TypeScript definitions, could you please add an item in `CHANGES.md` under "Fixes" with a short summary of the error that was fixed?

2025-01-06 23:36 UTC, NickCrews commented
@ggetz done, thank you!

2025-01-07 14:10 UTC, ggetz approved these changes

2025-01-07 14:11 UTC, ggetz commented
Perfect, thanks @NickCrews!

2025-01-07 14:12 UTC, merged